name: Build

on:
  push:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          repository: xuxiaocheng0201/dfg
          token: ${{ secrets.GH_TOKEN }}
          ref: 5980226978fb67b71fbe9d56e2fe70a18a22a1a9

      - name: Check rust version
        run: rustup --version

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Check flutter version
        run: flutter --version

      - name: Cache
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ./dfg_ui/rust/target/
            ./dfg_ui/.dart_tool/
            ./dfg_ui/build/
          key: dfg-release-windows-x86_64

      - name: Install cargo tools
        uses: taiki-e/install-action@v2
        with:
          tool: flutter_rust_bridge_codegen@2.11.1,cargo-expand

      - name: Generate code
        working-directory: ./dfg_ui
        run: |
          flutter_rust_bridge_codegen integrate --no-enable-integration-test
          git reset --hard
          flutter pub get
          flutter_rust_bridge_codegen generate
          flutter create --platforms=windows .

      - name: Build release
        working-directory: ./dfg_ui
        run: flutter build windows --release

      - name: Upload
        uses: actions/upload-artifact@v6
        with:
          path: dfg_ui/build/windows/x64/runner/Release
